fix for pthread detection problem due to libXmu detection for locations other than /usr/lib

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -182,15 +182,18 @@ if test "x${ac_cv_have_x}" = "x" ; then
     exit
 fi
 
-if ( ! ( test "x${ac_x_libraries}" = "x" ) ) ; then
-    ac_my_xmu_extra_libs="-L${ac_x_libraries}"
-fi
-if ( ! ( test "x${ac_x_includes}" = "x" ) ) ; then
-    ac_my_xmu_extra_libs="${ac_my_xmu_extra_libs} -I${ac_x_includes}"
-fi
+# first check for Xmu without tweaking
+AC_CHECK_LIB(Xmu,XmuClientWindow,,[unset ac_cv_lib_Xmu_XmuClientWindow; AC_CHECK_LIB(Xmu,XmuClientWindow,LDFLAGS="${LDFLAGS} -L{ac_x_libraries}",echo "libXmu required for drawing the frame around the area to capture" && exit 1,[-L${ac_x_libraries}])])
 
-AC_CHECK_LIB(Xmu,XmuClientWindow,,echo "libXmu required for drawing the frame around the area to capture" && exit,[${ac_my_xmu_extra_libs}])
-# libice test is present, but we need to bail out if not there
+#if ( ! ( test "x${ac_x_libraries}" = "x" ) ) ; then
+#    ac_my_xmu_extra_libs="-L${ac_x_libraries}"
+#fi
+#if ( ! ( test "x${ac_x_includes}" = "x" ) ) ; then
+#    ac_my_xmu_extra_libs="${ac_my_xmu_extra_libs} -I${ac_x_includes}"
+#fi
+
+#AC_CHECK_LIB(Xmu,XmuClientWindow,,echo "libXmu required for drawing the frame around the area to capture" && exit,[${ac_my_xmu_extra_libs}])
+## libice test is present, but we need to bail out if not there
 
 if test "x${ac_cv_lib_ICE_IceConnectionNumber+set}" = "x"; then
   echo "Your X11 environment is missing libice."
